service: user-api

provider:
  name: aws
  runtime: nodejs20.x
  profile: deploy-aws
  region: us-east-1

  environment:
    TABLE_NAME: users
    TABLE_ARN: arn:aws:dynamodb:us-east-1:992382566946:table/users
    QUEUE_URL: https://sqs.us-east-1.amazonaws.com/992382566946/create-user-queue
    QUEUE_ARN: arn:aws:sqs:us-east-1:992382566946:create-user-queue
    TOPIC_ARN: arn:aws:sns:us-east-1:992382566946:send-email-topic

resources:
  Resources:

    GetUsersRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: getUsersRole
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                Service: lambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: GetUsersPolicy
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action:
                    - dynamodb:Scan
                    - dynamodb:GetItem
                  Resource: ${self:provider.environment.TABLE_ARN}

    CreateUserRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: createUserRole
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                Service: lambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: CreateUserPolicy
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action:
                    - dynamodb:PutItem
                  Resource: ${self:provider.environment.TABLE_ARN}
                - Effect: Allow
                  Action:
                    - sqs:SendMessage
                  Resource: ${self:provider.environment.QUEUE_ARN}

    UpdateUserRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: updateUserRole
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                Service: lambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: UpdateUserPolicy
            PolicyDocument:
              Statement:
                - Effect: Allow
                  Action:
                    - dynamodb:UpdateItem
                  Resource: ${self:provider.environment.TABLE_ARN}

    DeleteUserRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: deleteUserRole
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                Service: lambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: DeleteUserPolicy
            PolicyDocument:
              Statement:
                - Effect: Allow
                  Action:
                    - dynamodb:DeleteItem
                  Resource: ${self:provider.environment.TABLE_ARN}

    SendEmailRole:
        Type: AWS::IAM::Role
        Properties:
          RoleName: enviarCorreosRole
          AssumeRolePolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Principal:
                  Service: lambda.amazonaws.com
                Action: sts:AssumeRole
          Policies:
            - PolicyName: EnviarCorreosPolicy
              PolicyDocument:
                Statement:
                  - Effect: Allow
                    Action:
                      - sqs:ReceiveMessage
                      - sqs:DeleteMessage
                      - sqs:GetQueueAttributes
                    Resource: ${self:provider.environment.QUEUE_ARN}
                  - Effect: Allow
                    Action:
                      - sns:Publish
                    Resource: ${self:provider.environment.TOPIC_ARN}

functions:

  # NODE
  getUsers:
    handler: node/getUsers.handler
    role: GetUsersRole
    events:
      - http:
          path: users
          method: get

  updateUser:
    handler: node/updateUser.handler
    role: UpdateUserRole
    events:
      - http:
          path: users/{id}
          method: put

  sendEmail:
    handler: node/sendEmail.handler
    role: SendEmailRole
    events:
      - sqs:
          arn: ${self:provider.environment.QUEUE_ARN}

          
  # JAVA
  createUser:
    handler: com.example.CreateUserHandler
    role: CreateUserRole
    runtime: java17
    package:
      artifact: ./java/target/user-api-1.0.jar
    events:
      - http:
          path: users
          method: post

  deleteUser:
    handler: com.example.DeleteUserHandler
    role: DeleteUserRole
    runtime: java17
    package:
      artifact: ./java/target/user-api-1.0.jar
    events:
      - http:
          path: users/{id}
          method: delete